version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure

    environment:
      POSTGRES_USER: 'nestspace'
      POSTGRES_PASSWORD: 'nestspace'
      POSTGRES_DB: 'nestspace'

    ports:
      - '5432:5432'
