version: "3.3"

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure

    environment:
      POSTGRES_USER: "notespace"
      POSTGRES_PASSWORD: "notespace"
      POSTGRES_DB: "notespace"

    ports:
      - "5432:5432"
